name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build plugin
        run: npm run build

      - name: Create release archive
        run: |
          cd dist
          zip -r ../obsidian-long-sentence-highlighter.zip .
          cd ..

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            obsidian-long-sentence-highlighter.zip
            dist/main.js
            dist/manifest.json
            dist/styles.css
          draft: false
          prerelease: false
          generate_release_notes: true